server:
  port: 9000
spring:
  application:
    name: CapitalPoolEureka

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # 不在注册中心注册自己
    register-with-eureka: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    root: debug
